import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry'
import { NavBar } from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Imersão 14 - Sistema de rastreabilidade de veículos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{
        <ThemeRegistry>
          <NavBar />
        {children}
        </ThemeRegistry>
      }</body>
    </html>
  )
}
